#!/bin/bash
#
# This builds all tests using testmanifest
# Tamio-Vesa Nakajima

# include the library
source lib

# include the configuration
source problemconfig

############################
# ARGUMENT PARSING
#############################

rebuild_inputs=true

while getopts "r:ho" opt; do
    case $opt in
        h)
            echo "Usage: ./run -r(estore) [revision to restore]"
            exit 0
            ;;
        r)
            rm -r tests
            unzip oldtests/$OPTARG.zip
            exit 0
            ;;
        o)
            rebuild_inputs=false
            ;;
    esac
done

read -p "Name of this test revision: " testrevision

# We will want to remember this:
currtest=0

# Loop over lines of 
cat testmanifest | while read instr; do
    # Parse a line of testmanifest
    set $instr
    numberoftests=$1
    incf=$2
    totalpoints=$3
    points=$(($totalpoints / $numberoftests))

    for nr in `seq $currtest $(($currtest + $numberoftests - 1))` ; do
        echo $nr
        #################
        # Build input:
        #################

        if [ $rebuild_inputs = true ] ; then
            # Build input generator
            cd ingen && make -s && cd ..

            # Copy ingen/ingen.bin and incf/$1 into stage
            cp ingen/ingen.bin stage/$problemname.bin
            cp incf/$incf stage/$problemname.cf

            # Build input
            cd stage && ./$problemname.bin && cp $problemname.in ../tests/$problemname-$nr.in && cd ..

            # Clean stage
            rm stage/*
        fi

        ###################
        # Build ok
        ###################

        # Build ok generator
        cd okgen && make -s && cd ..

        # Copy ok generator and input into stage
        cp okgen/okgen.bin stage/$problemname.bin
        cp tests/$problemname-$nr.in stage/$problemname.in

        # Indicate the number of points in the stage
        echo $points > stage/$problemname.points

        # Build ok
        cd stage && ./$problemname.bin && cd ..

        # Copy ok from stage into tests
        cp stage/$problemname.ok tests/$problemname-$nr.ok

        # Clean stage
        rm stage/*
    done

    #update currtest
    currtest=$(($currtest + $numberoftests))
done

if [ -n $testrevision ] ; then
    zip -r oldtests/$testrevision.zip tests/*
fi
