#!/bin/bash
#
# Tamio-Vesa Nakajima
# Builds test number $1 with incf $2
source problemconfig

nr=$1
incf=$2

# Build input generator
cd ingen && make -s && cd ..

# Make a stage
stage=$(mktemp -d)

# Copy ingen/ingen.bin and incf/$1 into stage
cp ingen/ingen.bin $stage/$problemname.bin
cp incf/$incf $stage/$problemname.cf

# Build input
currdir=$PWD
cd $stage && ./$problemname.bin && cp $problemname.in $currdir/tests/$problemname-$nr.in && cd $currdir

# Clean stage
rm -rf $stage
