#!/bin/bash
#
# Tamio-Vesa Nakajima

source problemconfig

# Evaluates the binary $1 with test $2, returning the message in $message, the time used in $timeUsed and the points in $points
binary=$1
testname=$2
timeUsed=$(./lib/run_src_test $binary $testname)


if (( $(echo "$timeUsed > $timelimit" | bc -l))) ; then
    # Set the return values
    # timeUsed is already set
    message=TLE
    points=0
else
    # Make the evaluator
    cd eval && make -s && cd ..

    # Copy the evaluator into the stage
    cp eval/eval.bin stage/eval.bin

    # Copy the ok file into the stage
    cp tests/$testname.ok stage/$problemname.ok

    # Create temporary files to hold the points and the eval message
    pointsFile=`mktemp`
    messageFile=`mktemp`

    # Enter the stage and evaluate, storing the results in $pointsFile and $messageFile
    cd stage && ./eval.bin > $pointsFile 2> $messageFile && cd ..

    # Set the return values
    # timeUsed is already set
    points=`cat $pointsFile`
    message=`cat $messageFile`
fi

echo $message $timeUsed $points
