#!/bin/bash
#
# Tamio-Vesa Nakajima
# Builds test number $1 with incf $2
build_test_number () {
    source problemconfig

    nr=$1
    incf=$2

    # Build input generator
    cd ingen && make -s && cd ..

    # Copy ingen/ingen.bin and incf/$1 into stage
    cp ingen/ingen.bin stage/$problemname.bin
    cp incf/$incf stage/$problemname.cf

    # Build input
    cd stage && ./$problemname.bin && cp $problemname.in ../tests/$problemname-$nr.in && cd ..

    # Clean stage
    rm stage/* 2> /dev/null

}


