#!/bin/bash
#
# Tamio-Vesa Nakajima
# Builds test number $1 with incf $2


# include the configuration
problemname=""
timelimit=""

# shellcheck disable=SC1091
source problemconfig

if [ -z "$problemname" ] || [ -z "$timelimit" ] ; then
    echo Bad config file
    exit 1
fi

nr=$1
incf=$2

# Build input generator
cd ingen && make -s && cd ..

# Make a stage
stage=$(mktemp -d)

# Copy ingen/ingen.bin and incf/$1 into stage
cp ingen/ingen.bin "$stage/$problemname.bin"
cp "incf/$incf" "$stage/$problemname.cf"

# Build input
currdir=$PWD
cd "$stage" || exit
./"$problemname.bin"
cp "$problemname.in" "$currdir/tests/$problemname-$nr.in"
cd "$currdir" || exit

# Clean stage
rm -rf "$stage"
