#!/bin/bash
#
# This builds all tests using testmanifest
# Tamio-Vesa Nakajima

# include the configuration
problemname=""
timelimit=""

# shellcheck disable=SC1091
source problemconfig

if [ -z "$problemname" ] || [ -z "$timelimit" ] ; then
    echo Bad config file
    exit 1
fi

############################
# ARGUMENT PARSING
#############################

rebuild_inputs=true

while getopts "r:ho" opt; do
    case $opt in
       h)
            echo "Usage: ./run -r(estore) [revision to restore]"
            exit 0
            ;;
        r)
            rm -r tests
            unzip "oldtests/$OPTARG.zip"
            exit 0
            ;;
        o)
            rebuild_inputs=false
            ;;
        *)
            echo "Bad options"
            exit 1
            ;;
 
    esac
done

read -p "Name of this test revision: " -r testrevision

# We will want to remember this:
currtest=0

# Loop over lines of 
while read -r instr; do
    # Parse a line of testmanifest
    # shellcheck disable=SC2086
    set $instr
    numberoftests=$1
    incf=$2
    totalpoints=$3
    points=$((totalpoints / numberoftests))

    for ((nr=$"currtest"; nr<"$currtest"+"$numberoftests" ; nr++))
    do
        echo $nr >&2

        if [ $rebuild_inputs = true ]
        then
            ./lib/build_test_number "$nr" "$incf"
        fi

        ./lib/build_ok_number $nr $points
    done

    #update currtest
    currtest=$((currtest + numberoftests))
done < testmanifest

if [ -n "$testrevision" ] ; then
    zip -r "oldtests/$testrevision.zip" tests/*
fi
