#!/bin/bash
#
# Runs sources on tests
# Tamio-Vesa Nakajima
#
# Use cases:
# ./run.sh -> runs all sources on all tests
# ./run.sh -s "a.cpp b.cpp" -s c.cpp -> runs a,b,c.cpp on all tests
# ./run.sh -t "00 01 02" -> runs all sources on tests 00, 01, 02
# ./run.sh -s a.cpp -t 00 -> runs a.cpp on 00

##########################
# GENERAL SETUP
#########################

# include the configuration
source problemconfig

############################
# ARGUMENT PARSING
#############################

# default values for used sources and used tests

srcs=""
tests=""

while getopts "hs:t:" opt; do
    case $opt in
        h)
            echo "Usage: ./run -s [source] -t [test]" >&2
            exit 0
            ;;
        s)
            for x in $OPTARG ; do
                srcs="$srcs $x"
            done
            ;;
        t)
            for x in $OPTARG ; do
                tests="$tests $problemname-$x"
            done
            ;;
        *)
            echo Bad option
            exit 1
            ;;
    esac
done
            
if [ -z "$srcs" ] ; then
    srcs=`ls -1 src | grep .cpp`
fi

if [ -z "$tests" ] ; then
    tests=`ls -1 tests | grep .in | awk -F '.' '{print $1}'`
fi

tests=`echo $tests | sort -t '-' -k 1 -n`


###########################
# EVALUATING
##########################

for src in $srcs ; do
    # Make a stage
    stage=$(mktemp -d)

    # Copy the source into the stage
    cp src/$src $stage/$problemname.cpp

    # Create a temporary file to hold the problem binary
    binary=`mktemp`

    # Build the source
    g++ $stage/$problemname.cpp -std=c++11 -o $binary -O2

    # Delete the stage
    rm -rf $stage

    # Make a temporary file to hold the table:
    table=`mktemp`

    # $table holds the score table
    echo $src > $table
    echo Test Message Time Points >> $table

    # For all tests
    for testname in $tests ; do
        # evaluate $binary on $testname, setting $message, $timeUsed, $points
        set "$(./lib/evaluate_src_test $binary $testname)"
        message=$1
        timeUsed=$2
        points=$3

        echo $testname.in $message $timeUsed $points >> $table
    done

    # Clear "Doing test ..."
    echo -en "\r                               \r" >&2

    # Output the table
    column -t $table

    # Calculate the score
    echo SCORE: `awk -F ' ' '$1 != "Test" {sum += 0 $4} END {print sum}' $table` >&2

    # Clear the temporary files
    rm $table
    rm $binary

done
